import React, { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Download, GraduationCap } from "lucide-react";
import { School, SchoolStudent } from "@/hooks/useSchool";
import jsPDF from "jspdf";

interface Result {
  id: string;
  subject: string;
  term: string;
  year: number;
  score: number;
  max_score: number;
  grade: string;
  teacher_comments: string | null;
}

interface Props {
  school: School;
  students: SchoolStudent[];
}

const ReportCard: React.FC<Props> = ({ school, students }) => {
  const [selectedStudent, setSelectedStudent] = useState("");
  const [selectedTerm, setSelectedTerm] = useState("Term 1");
  const [results, setResults] = useState<Result[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!selectedStudent) return;
    setLoading(true);
    (supabase as any).from("school_results").select("*")
      .eq("school_student_id", selectedStudent)
      .eq("term", selectedTerm)
      .order("subject")
      .then(({ data }: any) => { setResults(data || []); setLoading(false); });
  }, [selectedStudent, selectedTerm]);

  const student = students.find(s => s.id === selectedStudent);
  const avg = results.length ? Math.round(results.reduce((sum, r) => sum + r.score, 0) / results.length) : 0;

  const downloadPDF = () => {
    if (!student || !results.length) return;
    const doc = new jsPDF();
    const primary = school.primary_color || "#8B0000";

    // Header
    doc.setFillColor(primary);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text(school.name, 105, 18, { align: "center" });
    doc.setFontSize(10);
    doc.text("Student Report Card", 105, 28, { align: "center" });
    doc.text(`${selectedTerm} ${results[0]?.year || new Date().getFullYear()}`, 105, 34, { align: "center" });

    // Student info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Student: ${student.student_name}`, 20, 55);
    doc.text(`Class: ${student.class_name}`, 20, 63);
    doc.text(`Grade Level: ${student.grade_level}`, 120, 55);

    // Results table
    let y = 80;
    doc.setFillColor(primary);
    doc.rect(20, y - 6, 170, 10, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text("Subject", 25, y);
    doc.text("Score", 100, y);
    doc.text("Grade", 130, y);
    doc.text("Comments", 150, y);

    doc.setTextColor(0, 0, 0);
    results.forEach((r, i) => {
      y += 12;
      if (i % 2 === 0) { doc.setFillColor(245, 245, 245); doc.rect(20, y - 6, 170, 10, "F"); }
      doc.text(r.subject, 25, y);
      doc.text(`${r.score}/${r.max_score}`, 100, y);
      doc.text(r.grade, 135, y);
      if (r.teacher_comments) doc.text(r.teacher_comments.substring(0, 25), 150, y);
    });

    // Average
    y += 20;
    doc.setFontSize(14);
    doc.text(`Overall Average: ${avg}%`, 20, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Lana for Schools — ${school.website || ""}`, 105, 285, { align: "center" });

    doc.save(`${student.student_name}-${selectedTerm}-Report.pdf`);
  };

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3">
        <Select value={selectedStudent} onValueChange={setSelectedStudent}>
          <SelectTrigger><SelectValue placeholder="Select student" /></SelectTrigger>
          <SelectContent>{students.map(s => <SelectItem key={s.id} value={s.id}>{s.student_name} ({s.class_name})</SelectItem>)}</SelectContent>
        </Select>
        <Select value={selectedTerm} onValueChange={setSelectedTerm}>
          <SelectTrigger><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="Term 1">Term 1</SelectItem>
            <SelectItem value="Term 2">Term 2</SelectItem>
            <SelectItem value="Term 3">Term 3</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {loading && <div className="text-center py-8 text-muted-foreground">Loading results...</div>}

      {!loading && selectedStudent && results.length > 0 && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="flex items-center gap-2"><GraduationCap className="h-5 w-5" /> {student?.student_name} — {selectedTerm} Report</CardTitle>
            <Button variant="outline" className="gap-2" onClick={downloadPDF}><Download className="h-4 w-4" /> Download PDF</Button>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Subject</TableHead>
                  <TableHead>Score</TableHead>
                  <TableHead>Grade</TableHead>
                  <TableHead>Teacher Comments</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {results.map(r => (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium">{r.subject}</TableCell>
                    <TableCell>{r.score}/{r.max_score}</TableCell>
                    <TableCell><span className={`font-bold ${r.grade === "A" ? "text-green-600" : r.grade === "B" ? "text-blue-600" : r.grade === "C" ? "text-amber-600" : "text-red-600"}`}>{r.grade}</span></TableCell>
                    <TableCell className="text-muted-foreground">{r.teacher_comments || "—"}</TableCell>
                  </TableRow>
                ))}
                <TableRow className="font-bold bg-muted/50">
                  <TableCell>Overall Average</TableCell>
                  <TableCell>{avg}%</TableCell>
                  <TableCell></TableCell>
                  <TableCell></TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}

      {!loading && selectedStudent && !results.length && (
        <div className="text-center py-12 text-muted-foreground">
          <GraduationCap className="h-12 w-12 mx-auto mb-3 opacity-30" />
          <p>No results recorded for this term</p>
        </div>
      )}
    </div>
  );
};

export default ReportCard;
